name: Release Package to npm
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
    - run: yarn install
    - run: yarn build
    - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" | tee --append .npmrc
    - run: yarn semantic-release
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    publish:
    runs-on: ubuntu-latest
    before_script:
      - yarn install
      - |
        {
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}"
        } | tee --append .npmrc
    script:
      - yarn install
      - yarn build:webpack
      - yarn semantic-release
    only:
      refs:
        - main